sudo: required
dist: trusty
language: node_js

node_js:
  - '10'

apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

cache:
  directories:
    - node_modules
    - "$HOME/.npm"

env:
  global:
    - CHROME_BIN=chromium-browser
    - DISPLAY=:99.0

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - npm install -g @angular/cli@8.3.7
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

jobs:
  include:
    - stage: test
      script:
        - ng --version
        - ng lint
        - ng test --watch=false

    - stage: build-sandbox
      script:
        - ng build --configuration=sandbox
      after_success:
        - mv ./dist/runtime.*.js ./dist/runtime.bundle.js
        - mv ./dist/polyfills.*.js ./dist/polyfills.bundle.js
        - mv ./dist/polyfills-es5.*.js ./dist/polyfills-es5.bundle.js
        - mv ./dist/main.*.js ./dist/main.bundle.js
        - mv ./dist/styles.*.css ./dist/styles.bundle.css
      deploy:
        - provider: s3
          access_key_id:
            secure: IFSZ08iRSUQJexNsa7V60hTmzvricnGhBS3vbCTcPHy8L5sqOnAO49gtSoiDSMUjxYxXU1tpdqpI0h1nE4R+Fczd8vxjH87Z/lsVl0qKhsNYOXgdjJL/Yqz5hz3aAWOzYaZfJnvDPtzbqiC2BfSGT7FvVMJXIGgL9sSMEXZAJe8mIbyN3wUHHJJP780rCiAQESiu9i9asSUM7akJuZ47d4dyOth0hGoFvBVBtSHmX4vMvuruyQXgyCzMxY9ddpYjpUtk9W6PtrkL8lMVHnYVswDAMCr8bU4AiNvMnj0KylgxEwFtXHCSLI42jOZCBQa7P7HxFqPW20cWanDRaafAzvxlAz+HPJ66bSWoy91CpGU5ZpNBuAyl4mqYH5TgFlhQezsLrutd2X8dTizKUa2JRwhWSkJzWrtvBsX9qY5LLIAp9CE5FJGBVIfwHrv+zEtedv7m41HnQUA1IL+EjYODwyoVPrjzKM4Ykbep2ElFo7JsFoobYexfZCabI36X/l+rrByvpa7lFdDkElrWQWe9NneO4g5b7JkTtfwDDCKaSSwZT45Je4bJuKD+3cA3RH1hW7gJBghSdrjD2RZ773ctwLMDDHyWiN3XhF2XFr+ckhcmnCEAdBl0Ex7GKyyDsyYHw1krq5KKcr1wpxvaEcghtbfmL6lzAWVCTaux/yi9hho=
          secret_access_key:
            secure: PXixREqgPpnhcI3hDQwZshLm2R8tSKss6oM5AGUjW1vsSa7qK8Io3KbdXK1MDbRyFo1ed0fjKOnu1Fi6kMEmBcleuwY+vikuqhGrlA6XWxbLtqQaOdozURxNy8dnS2M/YZwi4DY9a7nc/rhkxqw6QKJjS31kbfhI4ZMVgh6XsvA2HyraiL3niqi2BfshsF71Xbm0ptBoRdnnTOqXeh+WYyEqCoxQhAteLEFhfKGHtp3Jm1SMYZHlu0KMTF+p1AR+Vac+QXJmPMpOW8kASMKV5SqMDQXYqck/wXZEaCmWyeHqRQhLqiyIuhY3tCQYznNOJayf6E8aZU2NGUis83tb7Ou2sLmxSoqPyTxOg44KGQ0oNuNW/Irph9J/0SX02j3FKnitgi6qRe7wRPPD+yN1s+7ydoG5xw5463z1VI6Yo0uTcUwRCoG61AeOFRfbRnO1y9rwLjCz54h+Rxq/qkL8Cz7IOlD+CLcLXIOaPiTmmHt8xxPlERyCyX96FYTOpcIAx6Qwx5ikNrNm/GBj+sicVQG8TuW+i9LQgcIOfMsf5ee4NmONa3ZU0LGLu8AUwlec5giAs18CwQavaWkfdFJFxe0xhBej23asKLoM9g0yZzoqAF587DlH/M+KV3iJQUAkCEP/7VQERjYOtmBNEFt+7+mY/ow9gcSiV1GhKcM8hZM=
          bucket: frontend-build-artifacts
          local-dir: dist
          upload-dir: sandbox
          acl: private
          skip_cleanup: true
          region: eu-west-1
          on:
            repo: Hub-of-all-Things/Rumpel
            branch: dev

    - stage: build-production
      script:
        - ng build --configuration=production
      after_success:
        - mv ./dist/runtime.*.js ./dist/runtime.bundle.js
        - mv ./dist/polyfills.*.js ./dist/polyfills.bundle.js
        - mv ./dist/polyfills-es5.*.js ./dist/polyfills-es5.bundle.js
        - mv ./dist/main.*.js ./dist/main.bundle.js
        - mv ./dist/styles.*.css ./dist/styles.bundle.css
      deploy:
        - provider: s3
          access_key_id:
            secure: IFSZ08iRSUQJexNsa7V60hTmzvricnGhBS3vbCTcPHy8L5sqOnAO49gtSoiDSMUjxYxXU1tpdqpI0h1nE4R+Fczd8vxjH87Z/lsVl0qKhsNYOXgdjJL/Yqz5hz3aAWOzYaZfJnvDPtzbqiC2BfSGT7FvVMJXIGgL9sSMEXZAJe8mIbyN3wUHHJJP780rCiAQESiu9i9asSUM7akJuZ47d4dyOth0hGoFvBVBtSHmX4vMvuruyQXgyCzMxY9ddpYjpUtk9W6PtrkL8lMVHnYVswDAMCr8bU4AiNvMnj0KylgxEwFtXHCSLI42jOZCBQa7P7HxFqPW20cWanDRaafAzvxlAz+HPJ66bSWoy91CpGU5ZpNBuAyl4mqYH5TgFlhQezsLrutd2X8dTizKUa2JRwhWSkJzWrtvBsX9qY5LLIAp9CE5FJGBVIfwHrv+zEtedv7m41HnQUA1IL+EjYODwyoVPrjzKM4Ykbep2ElFo7JsFoobYexfZCabI36X/l+rrByvpa7lFdDkElrWQWe9NneO4g5b7JkTtfwDDCKaSSwZT45Je4bJuKD+3cA3RH1hW7gJBghSdrjD2RZ773ctwLMDDHyWiN3XhF2XFr+ckhcmnCEAdBl0Ex7GKyyDsyYHw1krq5KKcr1wpxvaEcghtbfmL6lzAWVCTaux/yi9hho=
          secret_access_key:
            secure: PXixREqgPpnhcI3hDQwZshLm2R8tSKss6oM5AGUjW1vsSa7qK8Io3KbdXK1MDbRyFo1ed0fjKOnu1Fi6kMEmBcleuwY+vikuqhGrlA6XWxbLtqQaOdozURxNy8dnS2M/YZwi4DY9a7nc/rhkxqw6QKJjS31kbfhI4ZMVgh6XsvA2HyraiL3niqi2BfshsF71Xbm0ptBoRdnnTOqXeh+WYyEqCoxQhAteLEFhfKGHtp3Jm1SMYZHlu0KMTF+p1AR+Vac+QXJmPMpOW8kASMKV5SqMDQXYqck/wXZEaCmWyeHqRQhLqiyIuhY3tCQYznNOJayf6E8aZU2NGUis83tb7Ou2sLmxSoqPyTxOg44KGQ0oNuNW/Irph9J/0SX02j3FKnitgi6qRe7wRPPD+yN1s+7ydoG5xw5463z1VI6Yo0uTcUwRCoG61AeOFRfbRnO1y9rwLjCz54h+Rxq/qkL8Cz7IOlD+CLcLXIOaPiTmmHt8xxPlERyCyX96FYTOpcIAx6Qwx5ikNrNm/GBj+sicVQG8TuW+i9LQgcIOfMsf5ee4NmONa3ZU0LGLu8AUwlec5giAs18CwQavaWkfdFJFxe0xhBej23asKLoM9g0yZzoqAF587DlH/M+KV3iJQUAkCEP/7VQERjYOtmBNEFt+7+mY/ow9gcSiV1GhKcM8hZM=
          bucket: frontend-build-artifacts
          local-dir: dist
          upload-dir: live
          acl: private
          skip_cleanup: true
          region: eu-west-1

stages:
  - test
  - name: build-sandbox
    if: branch = dev
  - name: build-production
    if: branch = master
