language: node_js
node_js:
  - '7'

before_script:
  - npm install -g @angular/cli@1.3.0-rc.2

script:
  - ng lint
  - ng build --prod

deploy:
  - provider: s3
    access_key_id: AKIAISPMI5PZ5RW6NUQQ
    secret_access_key:
      secure: NeSalyWGvKgSRMu+iXeR61uW/YqA9k9TMfoTPt9hPQD5V1Q/ni5vLHj1Bj2jKG0JNdBD4WIux/s4faGzgW3ZeFK307eDs1VhgehKXQjfqyBNme973Zys+JXkHfpeRw3x1ujMREzQX9IRjKjhEQDCISBQNrP+ognxMPkronvs1bLtgOP5YSmZTOxcjgdsXj3JjkNnNAFEZPbBGnU5YelveAcB3Gtx7dO8dKJDsDPPF00YGZzC8cjL9xfJiblZ0YyJ/k5PB2uDCJpbZSzGs5tB+xpMFFBnNA2gyCjOOh5UMnPjPBo2BrzuSy8Zzuvu0DPiZlQEmPqIgVikK7rux4EDNzzv1K8+R0iMSnfrWYW6IPw0RrNcYKVdEqFU+vN3B3+eHvkNTF5e9AeoJoMEh39DaUuDC+1cYqaBzj9L/9zGaXOz31WY4ovhJpmoiT4r3rGgvAvVyWa09Eq4EMEcmYt4VPJpG9IDtf8ie+acIBSIGIKVFl6DhvhnByHeec4fJcTAfPEfD/+uwIGn92hjwvMzrlrrPFSQqvYHowfzOrSeZnESHeA88k2t3cyuHJ+Zyq+V8PlyWCWyEFsSVeC9MSmZEca+AFpc2k+JfHoNwkdwoewp6mS5yOmMaK/B3qzGPFABS8b65hGLCDv+0C1APpoAzMjYkd0fQmptdjJ1vBjnsx0=
    bucket: rumpel.hubat.net
    local-dir: dist
    acl: public_read
    skip_cleanup: true
    region: eu-west-1
    on:
      repo: Hub-of-all-Things/Rumpel
      branch: dev

  - provider: s3
    access_key_id: AKIAJ7UTSAOH4FZQNMCA
    secret_access_key:
      secure: EF8XUhgJk3+oeUN8EiwvlwI59tO0uhCk4g6ivcnXRK1KSGXvxOKu5j0lGfTcbM7LbFv6bOHDbV93+vNn21JwJuVVRIrA5yx57yfbyFaJ+XXkwygeJBs1e8tesIgsY4fvmNtMMBv0rgQU5RmK6WYeF5M5lLT8jGomVnywsadMS9+hqoLCRxAhc3o+BPMCMuyz8+fHa1Noh1WMLwBSOfYnJ1ODahqHUgHknKBk/mjlEzH3N22c1BnjR29hdayy3McSefADh8UdAErmV/zLG1fXjdmPm11hJpd5YX5XRCFUZop/gagFHO37gQ4Ix7d99mATdw5mNIRGHZDKChKkmMP4wvZmusSKyZlvagOrz/eNXnEwWz3xeRw3K9aw2ZP1Emhlk5xYOloA0S2+cpbPpMNZqLnPf+JSmGRSaVab9a4L5Rz0xoSSyCDS/JZyhb4DXUCE2QQsfVsG/qwoZtm4xJZ6vLW979KR0NnLle1Hgc4IKYJ8fD+NHC2Dmt+MG3Q2J5HxRiURV3VeaC9R9Q9IxgCFj1vxV+/WNKXRtH839Y+CUXT+Zx0C73Uh3bZB3AB4Z6k2sjyN616DzYdKxhXFgxaXHyTmUKhWb9WBIVQaZ2ZbNwHaabw/a+3WszdLl3hmLrBKPI1LlHPm5YSxAN3/uJiiqjkHhMYgJLA6w4f6deRJrUA=
    bucket: xtiva-rumpel.hubat.net
    local-dir: dist
    acl: public_read
    skip_cleanup: true
    region: eu-west-1
    on:
      repo: Hub-of-all-Things/Rumpel
      branch: xtiva

  - provider: s3
    access_key_id: AKIAJLFHYRO2WNJ52L5A
    secret_access_key:
      secure: S1pSMwVO3refssXi5hvM5t0BWGNOJLA93EiTKdMoRRPlnWLLnULYvex0NMu5aX3jjoCCI98q5TXl/d6KWuzj9RhYJ6SlJylJfWVvKOcnh8N/J0dccsbkxatwL2V2W7Ehg8wQCfCG7uU4G2++0ZRJXdOu3diUtopIiCuWEuRoGEZwUi93D+sGYa8rgvZuOgHQCoRNGDgVXtnVnRGx4ZAuu/+a7ies3GJoQ4FHJXEvU7z4cL41OYM38qfOk47P1/m/+KCwqw9qAWMcuhcFl/moIFTjj/c7Zw2+uRIz5Psw15uRTC4iu9IRCZxmmzOs67eCBfCf4ReZQIKGFj00OmvK3ChPAjdNgq5O34uu4Xj2N2izSdODIO1vvVZxECfqcnoDhpJpscAaWIe0s9Lf4l84djtkOShWE3wdRuyOFd9TEVR5g5m5uY7c8K3328z7LIkXYmZLAy4NkMn4XQyK4HeynwVw4THIAJ3NUFPQw1oR12IyXfRXo5ODAN+Zl0rDDwvgL0wRzuTABnAhU6vDpIZNMK0ixvOJBCqBHgHRRjK/A5jxjYTvNlLJqJ77X4XB2+WrB0OW3v3xgHjX5WLTmpLHG70rxjg4/Nwq13tBlJdeujJ7K6Ecu6PuBitU0EUp+FIQkuVfLx8t2/C877JyX83DwUV1jC/xNU+zagjnDfA/pCM=
    bucket: surreycode.hubat.net
    local-dir: dist
    acl: public_read
    skip_cleanup: true
    region: eu-west-1
    on:
      repo: Hub-of-all-Things/Rumpel
      branch: surreycode
